### Deploy a workflow file with a file type

POST http://localhost:5001/v1.0/invoke/zeebe-worker/method/command/deploy-workflow
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="fileContent"; filename="workflow.bpmn"

< ../workflow.bpmn
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="fileName"

workflow.bpmn
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="fileType"

bpmn
--WebAppBoundary--

### Deploy a workflow file without a file type

POST http://localhost:5001/v1.0/invoke/zeebe-worker/method/command/deploy-workflow
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="fileContent"; filename="workflow.bpmn"

< ../workflow.bpmn
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="fileName"

workflow.bpmn
--WebAppBoundary--